# Generated by Django 5.1.4 on 2025-01-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
